  - name: set prompt
    ansible.builtin.shell: set-prompt vault prometheus

  - name: Create Prometheus user
    ansible.builtin.user:
      name: Prometheus

  - name : download Prometheus
    ansible.builtin.unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.54.0/prometheus-2.54.1.linux-amd64.tar.gz
      dest: /opt
      remote_src: true
      owner: prometheus
      group: prometheus

  - name : Copy Prometheus systemd file
    ansible.builtin.template:
      src: node-exporter.service
      dest: /etc/systemd/system/prometheus.service


  - name : Start Prometheus service
    ansible.builtin.systemd_service:
      name: Prometheus
      state: restarted
      enabled: yes
      daemon-reload: yes

